added logging

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -4,22 +4,29 @@ set -eu
 ROOTDIR=$(dirname $(dirname $(realpath $0)))
 CFGFILE=$ROOTDIR/backup.cfg
 HOSTNAME=$(hostname)
+LOGFILE=$ROOTDIR/backup.log
 
-if [ ! -f $CFGFILE ] ; then
-  echo Config files does not exist: $CFGFILE
-  exit 1
-fi
+# functions #############
+error() {
+  printf '\E[31m'; echo "$@"; printf '\E[0m' | tee -a $LOGFILE
+}
 
-echo Using config file: $CFGFILE
-. $CFGFILE
+log() {
+  echo "$(date --rfc-3339=seconds): $@" | tee -a $LOGFILE
+}
+
+failure() {
+  error "Execution failed!"
+  exit -1
+}
 
 backup_dir() {
   TARGETPATH=$BACKUP_TARGET/$HOSTNAME/$1
-  echo Backing up $1 to $TARGETPATH ...
-  PASSPHRASE=""  duplicity --encrypt-sign-key $GPG_KEY_ID $1 $TARGETPATH
+  log "Backing up $1 to $TARGETPATH ..."
+  PASSPHRASE=""  duplicity --encrypt-sign-key $GPG_KEY_ID $1 $TARGETPATH | tee -a $LOGFILE
 }
 
-backup(){
+backup_dirs(){
   for d in ${SOURCE_DIRS[@]}
   do
     backup_dir $d
@@ -27,5 +34,21 @@ backup(){
 
 }
 
-backup
+# main #################
+trap failure EXIT
+
+if [ ! -f $CFGFILE ] ; then
+  error "Config files does not exist: $CFGFILE"
+  failure
+fi
+
+log "Using config file: $CFGFILE"
+. $CFGFILE
+
+
+backup_dirs
+
+log "Done."
+trap '' EXIT
+
 
